name: Validate Terraform

on:
  pull_request:

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Display envvars
        run: env

      - name: Terraform init
        run: terraform init

      - name: Validate Terraform
        run: terraform validate
